Add missing #include <cassert>
This fixes

  /build/source/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp: In member function 'virtual const String& Aws::Http::Standard::Stand>
  /build/source/aws-cpp-sdk-core/source/http/standard/StandardHttpRequest.cpp:72:5: error: 'assert' was not declared in this scope
       assert (iter != headerMap.end());
       ^~~~~~