Fix compile error when building core package
Building the core package on OS X using stock Clang reports the 3 errors because of missing class definition.
error: member access into incomplete type 'element_type' (aka 'Aws::Utils::Crypto::HashFactory')
error: member access into incomplete type 'element_type' (aka 'Aws::Utils::Crypto::HMACFactory')

Adding the necessary header files fixes the problem.