RetryStrategy.h: include <memory> for shared_ptr
On RHEL/CentOS 7, the default compiler is GCC 4.8.5, which results in
this compile error:

    In file included from /builddir/build/BUILD/aws-sdk-cpp-1.7.328/aws-cpp-sdk-core/include/aws/core/client/DefaultRetryStrategy.h:19:0,
                     from /builddir/build/BUILD/aws-sdk-cpp-1.7.328/aws-cpp-sdk-core/source/client/DefaultRetryStrategy.cpp:16:
    /builddir/build/BUILD/aws-sdk-cpp-1.7.328/aws-cpp-sdk-core/include/aws/core/client/RetryStrategy.h:40:32: error: 'shared_ptr' is not a member of 'std'
             typedef Utils::Outcome<std::shared_ptr<Aws::Http::HttpResponse>, AWSError<CoreErrors>> HttpResponseOutcome;

Include <memory> so that std::shared_ptr is available in the header
file.

The above error does not occur on other platforms (e.g. Fedora 31 with
GCC 9.3.1).