Stop using the now deprecated std::is_trivial.
std::is_trivial is deprecated in C++26. Using gcc 15 and C++26 yields
this warning:

/data/mwrep/res/mdw/SIOTF/internal/osp/aws_sdk/25-0-0-1/include/aws/core/utils/memory/AWSMemory.h: In function 'Aws::UniquePtr<T> Aws::MakeUnique(const char*, ArgTypes&& ...)':
/data/mwrep/res/mdw/SIOTF/internal/osp/aws_sdk/25-0-0-1/include/aws/core/utils/memory/AWSMemory.h:307:56: error: 'template<class _Tp> struct std::is_trivial' is deprecated: use 'is_trivially_default_constructible && is_triviall
y_copyable' instead [-Werror=deprecated-declarations]
  307 |         static_assert(!std::is_array<T>::value || std::is_trivial<T>::value,
      |                                                        ^~~~~~~~~~

So do as gcc suggests, and replace it by a combination of
is_trivially_default_constructible and is_trivially_copyable.