[aws-cpp-sdk-core]: fix missing include
AWSPartitions.h is missing a `cstddef` include. Not all compilers recognize `size_t`, causing errors like:

```
aws-cpp-sdk-core/include/aws/core/endpoint/AWSPartitions.h:17:22: error: 'size_t' does not name a type
   17 |         static const size_t PartitionsBlobStrLen;
      |                      ^~~~~~
aws-cpp-sdk-core/include/aws/core/endpoint/AWSPartitions.h:9:1: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
    8 | #include <aws/core/utils/memory/stl/AWSArray.h>
  +++ |+#include <cstddef>
    9 |
```

Fix by including the missing `cdstddef`.