Removed definition of JSON_USE_EXCEPTIONS
JSON_USE_EXCEPTIONS is exported to project which uses AWS SDK. If the project also uses JsonCpp
then JSON_USE_EXCEPTIONS may clash causing compilation error:

    /usr/include/aws/core/SDKConfig.h:18:0: error: "JSON_USE_EXCEPTION" redefined [-Werror]

According to issue #982, JsonCpp was replaced with another library cJSON. As a result JSON_USE_EXCEPTIONS
may be useless for AWS SDK.